version: '3.7'
services:
        db:
                # build: ./db
                image: mongo:4.2.7
                container_name: db
                ports:
                        - "27017:27017"
                volumes:
                        - db:/data/db
                networks:
                        iauu_net:
        api:
                build: ./api
                restart: always
                container_name: api
                command: npm run dev
                # volumes:
                #         - ./api:/usr/app
                #         - /usr/app/node_modules
                ports:
                        - "4444:4444"
                networks:
                        iauu_net:
                depends_on: 
                        - db
        web:
                build: ./web
                restart: always
                container_name: web
                command: npm run dev
                # volumes:
                #         - ./web:/usr/app
                #         - /usr/app/node_modules
                ports:
                        - "3000:3000"
                networks:
                        iauu_net:
                depends_on:
                        - api
        server:
                build: ./server
                container_name: server   
                restart: always                   
                ports:
                        - "8080:80"
                networks:
                        iauu_net:                             
                depends_on:
                        - api                
networks:
        iauu_net:        
volumes:
        db:        
