version: '3.7'
services:
        # lib: 
        #         build: ./api/lib
        #         container_name: lib
        #         volumes:
        #                 - ./api/lib:/usr/lib
        broker:
                image: rabbitmq:3-management-alpine
                container_name: broker
                ports:
                        - "5672:5672"
                        - "15672:15672"
                volumes:
                        - ./broker/data/:/var/lib/rabbitmq/
                        - ~/broker/logs/:/var/log/rabbitmq
                networks:
                        iauu_net:
        platform:                
                build: 
                        context: ./api
                        dockerfile: ./Dockerfile
                        args:
                                - service_path=./platform
                container_name: platform
                ports:
                        - "4444:4444"
                networks:
                        iauu_net:
                depends_on:
                        - broker
        mail:
                build: 
                        context: ./api 
                        dockerfile: ./Dockerfile
                        args:
                                - service_path=./mail
                container_name: mail
                networks:
                        iauu_net:
                depends_on:
                        - broker
        marketing:
                build: 
                        context: ./api 
                        dockerfile: ./Dockerfile
                        args:
                                - service_path=./marketing
                container_name: marketing
                networks:
                        iauu_net:
                depends_on:
                        - broker 
        chat:
                build: 
                        context: ./api
                        dockerfile: ./Dockerfile
                        args:
                                - service_path=./chat
                container_name: chat
                ports:
                        - "5555:5555"
                networks:
                        iauu_net:
                depends_on: 
                        - broker
        notifications:
                build: 
                        context: ./api
                        dockerfile: ./Dockerfile
                        args:
                                - service_path=./notifications
                container_name: notifications
                ports:
                        - "5556:5556"
                networks:
                        iauu_net:
                depends_on: 
                        - broker
        proxy:
                build: 
                        context: ./api
                        dockerfile: ./Dockerfile
                        args:
                                - service_path=./proxy
                container_name: proxy
                ports:
                        - "9999:9999"
                networks:
                        iauu_net:
                depends_on: 
                        - broker
        web:
               build: ./web
               container_name: web
               ports:
                       - "3000:3000"
               networks:
                       iauu_net:
               depends_on:
                       - platform
                       - chat
                       - mail
                       - proxy
        server:
                image: nginx:1.19
                container_name: server
                restart: always
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./server/app.conf:/etc/nginx/conf.d/default.conf
                        - ./server/certbot/conf:/etc/letsencrypt
                        - ./server/certbot/www:/var/www/certbot
                networks:
                        iauu_net:
                depends_on: 
                        - web
                        - platform
                        - mail
                        - chat
                        - proxy
        ssl:
                image: certbot/certbot
                container_name: ssl
                volumes:
                        - ./server/certbot/conf:/etc/letsencrypt
                        - ./server/certbot/www:/var/www/certbot
                depends_on:
                        - server
                entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
        iauu_net: