version: '3.7'
services:
        # db:
        #          build: ./db
        #          container_name: db
        #          ports:
        #                  - "27017:27017"
        #          volumes:
        #                  - db:/data/db
        #          networks:
        #                   iauu_net:
        api:
                build: ./api
                container_name: api
                ports:
                        - "4444:4444"
                        - "555:555"
                        - "999:999"
                networks:
                        iauu_net:
        web:
               build: ./web
               container_name: web
               ports:
                       - "3000:3000"
               networks:
                       iauu_net:
               depends_on:
                       - api
        server:
                image: nginx:1.19
                container_name: server
                restart: always
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./server/app.conf:/etc/nginx/conf.d/default.conf
                        - ./server/certbot/conf:/etc/letsencrypt
                        - ./server/certbot/www:/var/www/certbot
                networks:
                        iauu_net:
                depends_on: 
                        - web
                        - api
        broker:
                image: rabbitmq:3-management-alpine
                container_name: broker
                ports:
                        - 5672:5672
                        - 15672:15672
                volumes:
                        - ./broker/data/:/var/lib/rabbitmq/
                        - ~/broker/logs/:/var/log/rabbitmq
                networks:
                        iauu_net:
        ssl:
                image: certbot/certbot
                container_name: ssl
                volumes:
                        - ./server/certbot/conf:/etc/letsencrypt
                        - ./server/certbot/www:/var/www/certbot
                depends_on:
                        - server
                entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
        iauu_net:
volumes:
        db:
